{% set name = "xorg-libX11" %}
{% set version = "1.8.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: 69606f485c2c07c14ef64f75b7bb326d48587af33795d9ab3e607c0b5f94f11c

build:
  number: 0
  # configure.ac:3: error: Autoconf version 2.70 or higher is required
  # our latest m2-autoconf is 2.69.
  # xorg-libxdmcp and libxcb aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}
  detect_binary_files_with_prefix: true
  always_include_files:
    # Workaround for dummy X11 headers in OSX `tk` package.
    - include/X11/cursorfont.h
    - include/X11/ImUtil.h
    - include/X11/Xcms.h
    - include/X11/XKBlib.h
    - include/X11/XlibConf.h
    - include/X11/Xlib.h
    - include/X11/Xlibint.h
    - include/X11/Xlib-xcb.h
    - include/X11/Xlocale.h
    - include/X11/Xregion.h
    - include/X11/Xresource.h
    - include/X11/Xutil.h

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - autoconf
    - automake
    - gettext
    - libtool
    - sed
  host:
    - libxcb {{ libxcb }}
    - pthread-stubs ==0.3
    - xorg-util-macros == 1.20.2
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-xtrans == 1.6.0
  run:
    - xorg-xorgproto >=2024.1

test:
  commands:
    - test -f $PREFIX/lib/libX11.dylib  # [osx]
    - test -f $PREFIX/lib/libX11.so  # [linux]
    - test -f $PREFIX/lib/libX11-xcb.dylib  # [osx]
    - test -f $PREFIX/lib/libX11-xcb.so  # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libx11
  doc_url: https://www.x.org/releases/current/doc/libX11/libX11/libX11.html
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The main client library for X Windows version 11.
  description: |
    The main client library for X Windows version 11.

extra:
  recipe-maintainers:
    - pkgw
